#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
xset +fp /usr/share/fonts/local

xbacklight -set 30

export PATH=$PATH:~/bin

emacs --daemon &

owncloud &

dropbox start &

batterymon &

nm-applet &

keychain --agents gpg,ssh

# bell off
xset b off

synclient TapButton1=0  #disable tap clicking

# Change your keymap:
setxkbmap -layout us,es -variant altgr-intl, -option grp:alt_space_toggle -option grp_led:caps -option ctrl:nocaps

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/mgdelacroix/.fluxbox/log"
